
export const langResources = {
    fr: {
      tri: "Tri :",
      rechercher: "Rechercher...",
      types: "Types :",
      generation: "Génération :",
      aucun_resultat: "Aucun résultat",
      tous: "Tous",
      toutes: 'Toutes',
      poids: "Poids :",
      taille: "Taille :",
      chargement: "Chargement en cours...",
      erreur: "Erreur",
      lang_fr: "Français",
      lang_en: "Anglais",
      n_croissant: "Ordre croissant",
      n_decroissant: "Ordre décroissant",
      a_z: "Ordre alphabétique A-Z",
      z_a: "Ordre alphabétique Z-A",
      poids_croissant: "Poids croissant",
      poids_decroissant: "Poids décroissant",
      taille_croissant: "Taille croissante",
      taille_decroissant: "Taille décroissante",
      attaque: "Attaque",
      defense: "Défense",
      vitesse: "Vitesse",
      spe_atk: "Attaque spé.",
      spe_def: "Défense spé.",
      niveau: "Niveau",
    },
    en: {
      tri: "Sort :",
      rechercher: "Search...",
      types: "Types :",
      generation: "Generation :",
      aucun_resultat: "No results",
      tous: "All",
      toutes: 'All',
      poids: "Weight :",
      taille: "Height :",
      chargement: "Loading...",
      erreur: "Error",
      lang_fr: "French",
      lang_en: "English",
      n_croissant: "Ascending order",
      n_decroissant: "Descending order",
      a_z: "Alphabetical order A-Z",
      z_a: "Alphabetical order Z-A",
      poids_croissant: "Weight ascending",
      poids_decroissant: "Weight descending",
      taille_croissant: "Height ascending",
      taille_decroissant: "Height descending",
      attaque: "Attack",
      defense: "Defense",
      vitesse: "Speed",
      spe_atk: "Sp. Atk",
      spe_def: "Sp. Def",
      niveau: "Level",
    }
  }
  